# Generated by Django 6.0.3 on 2026-03-12 23:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco')),
                ('account_number', models.CharField(max_length=20, unique=True, verbose_name='Número de cuenta')),
                ('cci', models.CharField(blank=True, max_length=20, verbose_name='CCI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cuenta bancaria',
                'verbose_name_plural': 'Cuentas bancarias',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], max_length=10, verbose_name='Categoría')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('ruc_dni', models.CharField(blank=True, max_length=20, verbose_name='RUC / DNI')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('reference', models.TextField(blank=True, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EngineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('hourmeter', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Horómetro')),
                ('rpm_speed', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Velocidad RPM')),
                ('knot_speed', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Velocidad nudos')),
                ('fish_in_hold', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Pesca en bodega')),
                ('ambient_temp_engine_room', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. ambiente sala máquinas')),
                ('intake_air_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. aire admisión')),
                ('exhaust_pipe_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. tubo de escape')),
                ('oil_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión aceite')),
                ('oil_temp_crankcase', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. aceite cárter')),
                ('engine_coolant_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. refrigerante motor')),
                ('damper_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. damper')),
                ('boost_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión boots')),
                ('engine_oil_level', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Nivel aceite motor')),
                ('refill_engine_oil', models.BooleanField(default=False, verbose_name='Rellenar aceite motor')),
                ('coolant_pump_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión bomba refrigerante')),
                ('aftercooler_coolant_inlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. entrada refrigerante aftercooler')),
                ('aftercooler_coolant_outlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. salida refrigerante aftercooler')),
                ('liner_coolant_inlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. entrada refrigerante a las camisas')),
                ('liner_coolant_outlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. salida refrigerante a las camisas')),
                ('gearbox_coolant_inlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. entrada refrigerante caja transmisión')),
                ('gearbox_coolant_outlet_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. salida refrigerante caja transmisión')),
                ('exhaust_temp_cyl_1', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #1')),
                ('exhaust_temp_cyl_2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #2')),
                ('exhaust_temp_cyl_3', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #3')),
                ('exhaust_temp_cyl_4', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #4')),
                ('exhaust_temp_cyl_5', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #5')),
                ('exhaust_temp_cyl_6', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. escape cilindro #6')),
                ('gearbox_oil_pressure', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Presión aceite caja transmisión')),
                ('gearbox_oil_temp', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Temp. aceite caja transmisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de motor',
                'verbose_name_plural': 'Reportes de motor',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha')),
                ('buy_dollar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Compra dólar')),
                ('sell_dollar', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Venta dólar')),
                ('buy_euro', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Compra euro')),
                ('sell_euro', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Venta euro')),
            ],
            options={
                'verbose_name': 'Tipo de cambio',
                'verbose_name_plural': 'Tipos de cambio',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('service', 'Servicio'), ('product', 'Producto')], max_length=10, verbose_name='Categoría')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ítem',
                'verbose_name_plural': 'Ítems',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Solo lectura')], default='operator', max_length=20, verbose_name='Rol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField(verbose_name='Fecha de operación')),
                ('value_date', models.DateField(verbose_name='Fecha valor')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Importe')),
                ('itf', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ITF')),
                ('movement_number', models.CharField(blank=True, max_length=50, verbose_name='Número de movimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.bankaccount', verbose_name='Cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento bancario',
                'verbose_name_plural': 'Movimientos bancarios',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='api.item', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Entrada de inventario',
                'verbose_name_plural': 'Entradas de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(verbose_name='Detalle')),
                ('category', models.CharField(choices=[('expense', 'Egreso'), ('income', 'Ingreso')], max_length=10, verbose_name='Categoría')),
                ('voucher_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de comprobante')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_items', to='api.item', verbose_name='Ítem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Ítem de pago',
                'verbose_name_plural': 'Ítems de pago',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=50, verbose_name='Tipo de comprobante')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='Número de comprobante')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado')),
                ('voucher_pdf', models.FileField(blank=True, null=True, upload_to='purchases/vouchers/', verbose_name='Comprobante PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='api.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('detail', models.TextField(blank=True, verbose_name='Detalle')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_details', to='api.item', verbose_name='Ítem')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Detalle de compra',
                'verbose_name_plural': 'Detalles de compra',
            },
        ),
        migrations.CreateModel(
            name='PurchaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_pdf', models.FileField(upload_to='purchases/reports/', verbose_name='Informe PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.purchasedetail', verbose_name='Detalle')),
            ],
            options={
                'verbose_name': 'Informe de compra',
                'verbose_name_plural': 'Informes de compra',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(max_length=50, verbose_name='Tipo de comprobante')),
                ('voucher_number', models.CharField(max_length=50, verbose_name='Número de comprobante')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_process', 'En proceso'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.contact', verbose_name='Contacto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_details', to='api.item', verbose_name='Ítem')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.sale', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
            },
        ),
    ]
