# Generated by Django 6.0.3 on 2026-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginereport',
            name='aftercooler_coolant_inlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. entrada refrigerante aftercooler'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='aftercooler_coolant_outlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. salida refrigerante aftercooler'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='ambient_temp_engine_room',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. ambiente sala máquinas'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='boost_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión boots'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='coolant_pump_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión bomba refrigerante'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='damper_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. damper'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='engine_coolant_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. refrigerante motor'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='engine_oil_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Nivel aceite motor'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_pipe_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. tubo de escape'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #1'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #2'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #3'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #4'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #5'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='exhaust_temp_cyl_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. escape cilindro #6'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='fish_in_hold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pesca en bodega'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='gearbox_coolant_inlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. entrada refrigerante caja transmisión'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='gearbox_coolant_outlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. salida refrigerante caja transmisión'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='gearbox_oil_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión aceite caja transmisión'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='gearbox_oil_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. aceite caja transmisión'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='hourmeter',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='Horómetro'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='intake_air_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. aire admisión'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='knot_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Velocidad nudos'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='liner_coolant_inlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. entrada refrigerante a las camisas'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='liner_coolant_outlet_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. salida refrigerante a las camisas'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='oil_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Presión aceite'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='oil_temp_crankcase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Temp. aceite cárter'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='refill_engine_oil',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Rellenar aceite motor (0/1)'),
        ),
        migrations.AlterField(
            model_name='enginereport',
            name='rpm_speed',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='Velocidad RPM'),
        ),
    ]
