# Generated by Django 6.0.3 on 2026-03-18 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationperson',
            name='linked_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_person', to=settings.AUTH_USER_MODEL, verbose_name='Usuario vinculado'),
        ),
    ]
