# Generated by Django 6.0.3 on 2026-03-17 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enginereport_aftercooler_coolant_inlet_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Solo lectura')], default='operator', max_length=20, verbose_name='Rol')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token de registro')),
                ('token_used', models.BooleanField(default=False, verbose_name='Token usado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona de registro',
                'verbose_name_plural': 'Personas de registro',
                'ordering': ['-created_at'],
            },
        ),
    ]
